Abertay-MProf-2024/SEDA

Assets/Scripts/Counter.cs, Assets/Scripts/Counter.cs.meta, Assets/Scripts/PauseMenu.cs, Assets/UI/Pause_Settings Menu.prefab
The pause menu now actually pauses the game.
There is now also a placeholder for Audio in the pause/settings menu.
=> Pause | 11:17 | 23.05.24

Assets/Input/IA_DefaultControls.inputactions, Assets/Player/Main Camera.prefab, Assets/Scripts/CameraPan.cs, Assets/Scripts/CameraPan.cs.meta
=> Panning camera

Assets/Player/Main Camera.prefab, Assets/Scripts/CameraPan.cs, Assets/Scripts/PauseMenu.cs
Inverted the controls on the camera, and included a toggle that's exposed to the designers.
=> Camera Inverted Controls | 13:15 | 24.05.24

Assets/Scripts/PauseMenu.cs, Assets/Scripts/SettingsMenu.cs, Assets/UI/InGameSettingsButton.prefab, Assets/UI/InGameSettingsButton.prefab.meta, Assets/UI/Level Selection Canvas.prefab, Assets/UI/Pause_Settings Menu.prefab, Assets/UI/SceneManager.prefab, Assets/UI/SceneManager.prefab.meta
Created an InGameSettingsButton prefab that opens the Pause/Settings Menu, and added a function that returns to the Main Menu when you click the Main Menu button.
=> Quit To Main Menu Function | 14:55 | 24.05.24

Assets/Scripts/CameraPan.cs
I overcomplicated the solution :frowning:
But it's fixed now!!!!!! :smile:
=> Fixed Camera Pan Plane | 18:10 | 27.05.24

Assets/Scripts/CameraPan.cs
The answer was to be better at maths.
=> Camera Pan fixed! | 11:14 | 28.05.24

Assets/Scripts/TimeSystem.cs, Assets/Scripts/TimeSystem.cs.meta, Assets/UI/TimeDisplay.prefab, Assets/UI/TimeDisplay.prefab.meta
Added the passage of time! It's in the TimeDisplay prefab, using the TimeSystem script.
=> Real time change

Assets/Resource Definitions/Buildings/Logging Camp.asset, Assets/Resource Definitions/Buildings/Mine.asset, Assets/Resource Definitions/Buildings/WaterWell.asset, Assets/Resource Definitions/Buildings/WindTurbine.asset, Assets/Resource Definitions/Creatures/Cailleach.asset, Assets/Resource Definitions/Creatures/Giant.asset, Assets/Resource Definitions/Creatures/Kelpie.asset, Assets/Resource Definitions/Resources/Cow.asset, Assets/Resource Definitions/Resources/Forest.asset, Assets/Resource Definitions/Resources/Oats.asset, Assets/Resource Definitions/Resources/Rock.asset, Assets/Scenes/UI Screen.unity, Assets/Scripts/BuildingSystem/BuildSystem.cs, Assets/Scripts/BuildingSystem/BuildingTypeSelect.cs, Assets/Scripts/CameraPan.cs, Assets/Scripts/Grid System/GridObject.cs, Assets/Scripts/Inventory.cs, ProjectSettings/ProjectSettings.asset
There might be some conflicts again... :) @rinku176
=> Fixed bug involving inventory not resetting on level reload.

Assets/Prefabs/UI/ResourceUI.prefab, ProjectSettings/ProjectSettings.asset
- Changed project settings to reduce build times
- Added LevelSettings script to ResourceUI prefab so designers can set the amount of time before the level ends in the inspector.
- Increased the size of the Creature buttons
- Added a Cailleach to the map so that all creatures can be tested
=> Friday21stBuild01

Assets/Prefabs.meta, Assets/Prefabs/UI.meta, Assets/Prefabs/UI/ResourceUI.prefab.meta, Assets/Resource Definitions/AudioController.prefab.meta, Assets/Resource Definitions/LevelManager.prefab.meta
Aligned the islands and objects to the grid in the scene "Island_A"
Textures for island pieces and most UI is missing.
=> Dom align level - "Island_A"

Assets/Prefabs/UI/Canvas_Game scene UI.prefab, Assets/Resource Definitions/Buildings/Logging Camp.prefab, Assets/Resource Definitions/Buildings/WaterWell.prefab, Assets/Resource Definitions/Resources/RuinedBuildings.prefab, Assets/Resource Definitions/Resources/SpringBarley.prefab, Assets/Resource Definitions/SoilGrades/PeasAndBeans.prefab
-- Fixed null ref exceptions
-- Added Time Pause and Skip
=> AlphaFixes | 18:44 | 02.07.24

Assets/Scripts/Inventory.cs
-- Thunderstorm begins immediately and lasts until the end of the month.
=> Cailleach Thunderstorm Happens Immediately | 12:42 | 03.07.24

Assets/Prefabs/UI/Level Selection Canvas.prefab, Assets/Scripts/Menus and UI/LevelSelect.cs
-- Each level select button now points to the correct level.
=> LevelSelection Bugfix | 14:56 | 10.07.24

Assets/Scripts/InputManager.cs
-- Clicking on a UI element prevents other input
=> Fixed UI Click-through | 14:08 | 11.07.24

Assets/Editor/LevelManagerEditor.cs, Assets/Scripts/InputManager.cs
-- Fixed LevelManager missing input
-- Fixed InputManager nullref exception
=> Fixed Input Bugs | 14:36 | 11.07.24

ProjectSettings/QualitySettings.asset
-- Turned Realtime Reflection Probes on for Balanced graphics settings
=> Fixed Ocean Foam | 16.07.24

Assets/Scripts/WeatherSystem.cs
=> Fixed Restart Weather Bug | 13:01 | 17.07.24

Assets/Scripts/MusicManager/AudioZoomController.cs, Assets/Scripts/TerrainSystem/Tilesystem.cs
-- Removed Allowed Soil Grade List
=> Fixed Soil Grade Change | 17:19 | 18.07.24

Assets/Textures/Tiles/T_GroundGrassTiling02a_C.png, Assets/Textures/Tiles/T_GroundGrassTiling02a_C.png.meta, Assets/Textures/Tiles/T_GroundGrassTiling02b_C.png, Assets/Textures/Tiles/T_GroundGrassTiling02b_C.png.meta
=> Imported new ground textures

Assets/Prefabs/UI/Level Selection Canvas.prefab
Created 3 separate level select UI with text for each.
=> Updated Text For level select screen | 19.07.24 | 14:38

Assets/Prefabs/UI/Resource Popup.prefab
-- Bug: Resource Popup was hidden behind grid and ocean.
-- Fix: Resource Popup now renders in front of everything
=> Fixed Resource Popup Rendering Issue | 10:53 | 22.07.24

Assets/Prefabs/Scene/StandingStone.prefab, Assets/Scripts/StandingStone.cs
-- Standing Stone VFX was broken in Levels 2 and 3. It now plays correctly
=> Fixed Broken Standing Stone VFX | 11:26 | 23.07.24

Assets/Meshes/Tiles/STM_TileRiverCoastRunoff01a.fbx, Assets/Meshes/Tiles/STM_TileRiverCoastRunoff01a.fbx.meta, Assets/Meshes/Tiles/STM_TileRiverCoastRunoff01b.fbx, Assets/Meshes/Tiles/STM_TileRiverCoastRunoff01b.fbx.meta, Assets/Meshes/Tiles/STM_TileRiverMountainRunoff01a.fbx, Assets/Meshes/Tiles/STM_TileRiverMountainRunoff01a.fbx.meta, Assets/Textures/Tiles/RiverTiles/T_TileRiverTilingVertical02a_C.png, Assets/Textures/Tiles/RiverTiles/T_TileRiverTilingVertical02a_C.png.meta
added new water texxture and meshes for mountain and coastal rivers
=> 3 d art otto water improvements

Assets/Materials/Tiles/M_TileMaster01a.mat, Assets/Polybrush Data/Color Palette/ColorPalette-Default.asset, Assets/Shaders/SH_TileMasterShader01.shadergraph, Assets/Textures/Tiles/T_TileBuildingGravel01a.png, Assets/Textures/Tiles/T_TileBuildingGravel01a.png.meta
masked using an inverse blue channel of vertex colours (0 has gravel, 1 does not)
=> adjusted master shader to add gravel for playable tiles

Assets/Prefabs/UI/Canvas_Game scene UI.prefab, Assets/Prefabs/UI/Level Selection Canvas.prefab, Assets/Scenes/UI4/Icon_Peas&Beans.png, Assets/Scenes/UI4/Icon_Peas&Beans.png.meta, Assets/Scenes/UI4/Level_Select_Icon_01.png, Assets/Scenes/UI4/Level_Select_Icon_01.png.meta, Assets/Scenes/UI4/Level_Select_Icon_02.png, Assets/Scenes/UI4/Level_Select_Icon_02.png.meta, Assets/Scenes/UI4/Level_Select_Icon_03.png, Assets/Scenes/UI4/Level_Select_Icon_03.png.meta
Modified the Canvas_Game scene UI and Level Selection Canvas prefabs, and added new art assets
=> Level button art material implementation | 10:17 | 25.07.2024

Assets/Shaders/SH_TileMasterShader01.shadergraph
added rim highlight for mountains
changed vertex colours to sliders
=> changed ground shader parameters

Assets/Prefabs/UI/Canvas_Game scene UI.prefab, Assets/Scenes/UI_Art Asset/NEW Kelpie Colours and Lines Illustration Large 2.0.png, Assets/Scenes/UI_Art Asset/NEW Kelpie Colours and Lines Illustration Large 2.0.png.meta
Updated Kelpie illustration image, modified Canvas_Game scene UI, added new art assets
=> Kelpie illustration Update | 10:24 |30.7.2024

Assets/VFX/CreatureTiles/FAB_CaillachTile.prefab, Assets/VFX/CreatureTiles/FAB_GiantTile 2.prefab
-- Added Cailleach Icon to the Cailleach Prefab
-- Made Giant size 2x1 tiles
=> Fixed Creature Tile Bugs | 13:41 | 31.07.24
